# Generated by Django 3.1.7 on 2021-04-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Closet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('cover', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
